name: react ci-cd for dev
env:
  DOCKERHUB_REGISTRY_USER: swetank01
  DOCKERHUB_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  IMAGE_REPO_NAME: "react"

on:
  push:
      branches: [ "dev" ]
    paths:
      - "src/client/Dockerfile"
      - "src/client**"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Chart Checkout
        uses: actions/checkout@v2
  
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      

      - name: Build the Docker image
        run: |
          docker build . --file ./src/client/Dockerfile --build-arg TAG=$GITHUB_REF_SLUG --tag $DOCKERHUB_REGISTRY_USER/$IMAGE_REPO_NAME:$GITHUB_REF_SLUG
  push:
    runs-on: ubuntu-20.04
    depend-on: build
    steps:          
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_REGISTRY_USER }}
          password: ${{ env.DOCKERHUB_REGISTRY_PASSWORD }}
      
      - name: Docker Push
        run: docker push $DOCKERHUB_REGISTRY_USER/$IMAGE_REPO_NAME:$GITHUB_REF_SLUG
