name: PR - Dependency Check
on: 
  pull_request:

jobs:
  build-test:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

#     NODE
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
          cache-dependency-path: src/client/yarn.lock

      - name: Install node modules
        working-directory: src/client
        run: yarn install --frozen-lockfile
