name: react-cache
env:
  DOCKERHUB_REGISTRY_USER: swetank01
  DOCKERHUB_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  IMAGE_REPO_NAME: "react-cache"

on:
  push:
    branches: 
      - dev
      - qa
      - main
    paths:
      - ".github/workflows/react-cache.yml"
      - "deployment/react-cache/Dockerfile"
      - "src/client/package.json"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Chart Checkout
        uses: actions/checkout@v2
  
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      

      - name: Build the Docker image
        run: |
          docker build . --file ./deployment/react-cache/Dockerfile --tag $DOCKERHUB_REGISTRY_USER/$IMAGE_REPO_NAME:$GITHUB_REF_SLUG

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_REGISTRY_USER }}
          password: ${{ env.DOCKERHUB_REGISTRY_PASSWORD }}
      
      - name: Docker Push
        run: docker push $DOCKERHUB_REGISTRY_USER/$IMAGE_REPO_NAME:$GITHUB_REF_SLUG
